#ifndef _CONFIG_H_
#define _CONFIG_H_

#define MAP_FOLDER L"resources/map/"

//GRAVITY
#define GRAVITY 0.03f

//BILL 
#define BILL_VX 0.1f
#define BILL_VY 9.5f

//BULLET
#define BULLET_REINFORCE 0.05f

#define BULLET_N_V 0.25f
#define BULLET_N_COUNT 4

#define BULLET_S_COUNT 10
#define BULLET_S_COUNT_ONE_SHOOT 5
#define BULLET_S_ELAPSED_DEGREES 10
#define BULLET_S_V 0.2f
#define BULLET_S_ELAPSED_TIME 100

#define BULLET_F_V 0.2f
#define BULLET_F_R 18
#define BULLET_F_ELAPSED_DEGREES 30

#define BULLET_L_V 0.32f
#define BULLET_L_ELAPSED_DIS 10

#define BULLET_M_V 0.3f

//GROUND
#define GROUND_BOUNDS_ATHWART 0
#define GROUND_TIME_EFFECT 300

#define GROUND_BRIDGE_DESTROY_EFFECT_COUNT 4
#define GROUND_BRIDGE_ELAPSED_RANDOM_POSITION 14
#define GROUND_BRIDGE_DESTROY_TIME 800
#define GROUND_BRIDGE_DISTANCE_DESTROY 32

//EFFECT 
#define EFFECT_DESTROY_TIME 200

#endif