#ifndef _CONFIG_H_
#define _CONFIG_H_

#define MAP_FOLDER L"resources/map/"

//GRAVITY
#define GRAVITY 0.011f

//BILL 
#define BILL_VX 0.055f
#define BILL_VY 5.95f	
#define BILL_VY_DIE  5.0f
#define BILL_DISTANCE_GROUND 16
#define BILL_REVIVAL_TIME 2500

//BULLET
#define BULLET_REINFORCE 0.025f

#define BULLET_N_V 0.18f
#define BULLET_N_TOTAL 4

#define BULLET_S_TOTAL 10
#define BULLET_S_COUNT_ONE_SHOOT 5
#define BULLET_S_ELAPSED_DEGREES 10
#define BULLET_S_V 0.2f
#define BULLET_S_ELAPSED_TIME 100

#define BULLET_F_V 0.1f
#define BULLET_F_R 16
#define BULLET_F_ELAPSED_DEGREES 25
#define BULLET_F_TOTAL 4

#define BULLET_L_V 0.25f
#define BULLET_L_ELAPSED_DIS 10
#define BULLET_L_TOTAL 3

#define BULLET_M_V 0.25f
#define BULLET_M_TOTAL 4

#define BULLET_NE_V 0.08f
#define BULLET_NE_TOTAL 30

#define BULLET_B_VX 0.04f
#define BULLET_B_RANDOM_VX 50
#define BULLET_B_VY 5.0f
#define BULLET_B_TOTAL 4

#define BULLET_B2_V 0.07f
#define BULLET_B2_TOTAL 4

#define BULLET_ME_V 0.07f
#define BULLET_ME_TOTAL 4

#define BULLET_SP_TOTAL 15
#define BULLET_SP_VX 0.042f
#define BULLET_SP_VY 0.15f
#define BULLET_SP_VY_SPLIT 4.5f

//GROUND
#define GROUND_SIZE_NORMAL_X 32
#define GROUND_SIZE_NORMAL_Y 16
#define GROUND_TIME_EFFECT 300

#define GROUND_BRIDGE_DESTROY_EFFECT_COUNT 3
#define GROUND_BRIDGE_ELAPSED_RANDOM_POSITION 14
#define GROUND_BRIDGE_DESTROY_TIME 1100
#define GROUND_BRIDGE_DISTANCE_DESTROY 32

#define GROUND_ROCK_FLY_VX 0.05f

//EFFECT 
#define EFFECT_DESTROY_TIME 300

//ENEMY
#define ENEMY_ATTACK_DISTANCE 120
#define ENEMY_ATTACK_DEGREES 30
#define ENEMY_VY_DIE 5.1f

#define ENEMY_SNIPER_STAND_MAX_BULLET 3
#define ENEMY_SNIPER_STAND_ELAPSED_SHOOT 300

#define ENEMY_SNIPER_HIDE_MAX_BULLET 1
#define ENEMY_SNIPER_HIDE_TIME_WAIT 2000

#define ENEMY_SNIPER_WATER_MAX_BULLET 3
#define ENEMY_SNIPER_WATER_TIME_WAIT 2000
#define ENEMY_SNIPER_WATER_DISTANCE_ATTACK 50

#define ENEMY_SNIPER_BOSS_MAX_BULLET 3
#define ENEMY_SNIPER_BOSS_TIME_WAIT 2000
#define ENEMY_SNIPER_BOSS_ELAPSED_SHOOT 300

#define ENEMY_GROUND_CANON_MAX_BULLET 3
#define ENEMY_GROUND_CANON_ELAPSED_SHOOT 300

#define ENEMY_WALL_TURRET_MAX_BULLET 1
#define ENEMY_GROUND_CANON_ELAPSED_SHOOT 300

#define ENEMY_RUN_MAN_VX 0.07f
#define ENEMY_RUN_MAN_VY 3.5f
#define ENEMY_RUN_MAN_BOUNDS_WIDTH 14
#define ENEMY_RUN_MAN_BOUNDS_HEIGHT 22
#define ENEMY_RUN_MAN_TOTAL 5
#define ENEMY_RUN_MAN_DISTANCE_ACTIVE 50
#define ENEMY_RUN_MAN_ELAPSED_TIME_ATTACK 1500

#define ENEMY_RUN_MAN_FIRE_MAX_BULLET 1
#define ENEMY_RUN_MAN_FIRE_TOTAL 2
#define ENEMY_RUN_MAN_FIRE_ATTACK_DISTANCE 50
#define ENEMY_RUN_MAN_FIRE_TIME_WAIT 1500

#define ENEMY_FIRE_VX 0.05f 

#define ENEMY_BOOM_THROW_VX 0.03f
#define ENEMY_BOOM_THROW_VY 2.50f
#define ENEMY_BOOM_THROW_GRAVITY 0.003f

#define ENEMY_ROCK_ROLL_GRAVITY 0.005f


//BACKGROUND
#define BG_TILED_WIDTH 16
#define BG_TILED_HEIGTH 16

// ITEM
#define ITEM_STAND_VY_ENABLE 6.7f
#define ITEM_STAND_VX_ENABLE 0.042f

#define ITEM_FLY_VX_MOVE 0.1f
#define ITEM_FLY_VY_MOVE 0.08f
#define ITEM_FLY_ANGLE 10 
#define ITEM_FLY_BOUND_COS 3
#define ITEM_FLY_VX_DIE 0.02f
#define ITEM_FLY_VY_DIE 6.2f

// BOSS
#define BOSS1_SPACE_X 36
#define BOSS1_SPACE_Y 36
#define BOSS1_SPACE_DESTROY_X 15
#define BOSS1_SPACE_DESTROY_Y 30
#define BOSS1_NUMBER_DESTROY 8
#define BOSS1_GUN_MAX_BULLET 2
#define BOSS1_GUN_ELAPSED_SHOOT 300
#define BOSS2_DELTA_ANGLE 6
#define BOSS2_ELAPSED_CHANGE 2000
#define BOSS2_ARM_MAX_BULLET 1
#define BOSS2_V_BOOT 0.05f
#endif