#ifndef CRESOURCEID_H
#define CRESOURCEID_H

enum ResourceID
{
	// background
	RESID_BG1,
	RESID_BG2,
	RESID_BG3,

	// bill
	RESID_BILL_DIE,
	RESID_BILL_IN_WATER,
	RESID_BILL_JUMP,
	RESID_BILL_MOVE,
	RESID_BILL_STAND,

	// item
	RESID_ITEM_FLY,
	RESID_ITEM_STAND,

	// enemy
	RESID_ENEMY_FIRE,
	RESID_ENEMY_GROUND_CANNON,
	RESID_ENEMY_ROCK_ROLL,
	RESID_ENEMY_RUN_MAN,
	RESID_ENEMY_RUN_MAN_FIRE,
	RESID_ENEMY_SINPER_HIDE,
	RESID_ENEMY_SINPER_STAND,
	RESID_ENEMY_WALL_TURRET,
	RESID_ENEMY_SNIPER_BLOCK,
	RESID_ENEMY_BOOM_THROW,
	RESID_ENEMY_SNIPER_BOSS,
	RESID_ENEMY_TANK,
	RESID_ENEMY_SNIPER_WATER,

	// ground
	RESID_GROUND_GRASS,
	RESID_GROUND_BRIDGE,	//nước nhấp nháy
	RESID_GROUND_ELECTRON,
	RESID_GROUND_ROCK_FLY,
	RESID_GROUND_WATER,


	// effect
	RESID_EFFECT_DESTROY,
	RESID_EFFECT_DIE,
	RESID_EFFECT_SHOOT,
	RESID_EFFECT_STAR,
	RESID_EFFECT_WATER,
	RESID_EFFECT_WATERFALL,

	// bullet
	REDID_BULLET_B,
	REDID_BULLET_F,
	REDID_BULLET_L,
	REDID_BULLET_M,
	REDID_BULLET_N,
	REDID_BULLET_NE,
	REDID_BULLET_S,
	REDID_BULLET_B2,

	// boss
	RESID_BOSS_1,	
	RESID_BOSS_2,
	RESID_BOSS_3

};

#endif
