#ifndef CRESOURCEID_H
#define CRESOURCEID_H

enum ResourceID
{
	// background
	RESID_BG1,
	RESID_BG2,
	RESID_BG3,

	// bill
	RESID_BILL_DIE,
	RESID_BILL_IN_WATER,
	RESID_BILL_JUMP,
	RESID_BILL_MOVE,
	RESID_BILL_STAND,

	// item
	RESID_ITEM_FLY,
	RESID_ITEM_STAND,

	// enemy
	RESID_ENEMY_FIRE,
	RESID_ENEMY_GROUND_CANNON,
	RESID_ENEMY_ROCK_ROLL,
	RESID_ENEMY_RUN_MAN,
	RESID_ENEMY_SINPER_HIDE,
	RESID_ENEMY_SINPER_STAND,
	RESID_ENEMY_WALL_TURRET,	

	// ground
	RESID_GROUND_GRASS,
	RESID_GROUND_BRIDGE,
	RESID_GROUND_EFFECT1, //nước nhấp nháy
	RESID_GROUND_ELECTRON,
	RESID_GROUND_STAR,
	RESID_GROUND_ROCK_FLY,
	RESID_GROUND_WATER,

	// effect
	RESID_EFFECT_DESTROY,
	RESID_EFFECT_DIE,
	RESID_EFFECT_SHOOT,

	// bullet
	REDID_BULLET_B,
	REDID_BULLET_F,
	REDID_BULLET_L,
	REDID_BULLET_M,
	REDID_BULLET_N,
	REDID_BULLET_NE,
	REDID_BULLET_S,

	// boss
	RESID_BOSS_1_BG,
	RESID_BOSS_1_BADGE,
	RESID_BOSS_1_GUN,

	


};

#endif
